---
title: "Statistical analysis"
output: html_notebook
---

First of all, EDY was calculated for the male individuals in the data set, as explained in the vignette. Next, EDY status was compared with the exposition data, during pregnancy and after birth. 

The association analysis were performed as follows: 

```
libray(rexposome)
library(compareGroups)

# edy.transcriptome_subcohort_notfitr is the EDY object created by getEDY
EDY.status <- data.frame(edy.transcriptome_subcohort_notfitr$EDY)
names(EDY.status) <- c("EDY.status")

# exppostnatal is the ExposomeSet with data about the exposition after birth
exp.matrix <- merge(expos(exppostnatal), EDY.status, by.x="row.names", by.y="row.names")

# Here we compare EDY.status with all the variales in exppostnatal
tt <- compareGroups(EDY.status ~ ., data = exp.matrix)
createTable(tt)
```

The function `compareGroups` performs descriptives by groups for several variables.
Depending whether the row-variable is considered as continuous normal-distributed (1), continuous non-normal distributed (2) or categorical (3), the following descriptives and tests are performed: 

1. mean, standard deviation and t-test or ANOVA 
2. median, 1st and 3rd quartiles (by default), and Kruskall-Wallis test 
3. or absolute and relative frequencies and chi-squared or exact Fisher test when the expected frequencies is less than 5 in some cell

Also, a row-variable can be of class `Surv`. Then the probability of `event` at a fixed time (set up with `timemax` argument) is computed and a logrank test is performed.


When there are more than 2 groups, it also performs pairwise comparisons adjusting for multiple testing (Tukey when row-variable is normal-distributed and Benjamini & Hochberg method otherwise), and computes p-value for trend. The p-value for trend is computed from the Pearson test when row-variable is normal and from the Spearman test when it is continuous non normal. If row-variable is of class 'Surv', the score test is computed from a Cox model where the grouping variable is introduced as an integer variable predictor. If the row-variable is categorical, the p-value for trend is computed as 
$1-pchisq(cor(as.integer(x),as.integer(y))^2*(length(x)-1),1)$ 
where `x` is the row-variable and `y` is the grouping variable. 
If there are two groups, the Odds Ratio is computed for each row-variable. While, if the response is of class `Surv` (i.e. time to event) Hazard Ratios are computed. 
The p-values for Hazard Ratios are computed using the logrank or Wald test under a Cox proportional hazard regression when row-variable is categorical or continuous, respectively. 


